const createNameTag  = {
    UPDATENAME_DATA_SUCCESS : "UPDATENAME_DATA_SUCCESS",
    UPDATENAME_DATA_FAILURE : "UPDATENAME_DATA_FAILURE",
    
  };

const createAgeTag = {
    UPDATE_AGE_SUCCESS : "UPDATE_DATA_SUCCESS",
    UPDATE_AGE_FAILURE : "UPDATE_AGE_FAILURE"

}

const createLocationTag = {
    UPDATE_LOCATION_SUCCESS : "UPDATE_LOCATION_SUCCESS",
    UPDATE_LOCATION_FAILURE : "UPDATE_LOCATION_FAILURE"

}

const createGuestsTag = {
    UPDATE_GUESTS_SUCCESS : "UPDATE_GUESTS_SUCCESS",
    UPDATE_GUESTS_FAILURE : "UPDATE_GUESTS_FAILURE"

}

const createAddressTag = {
    UPDATE_ADDRESS_SUCCESS : "UPDATE_ADDRESS_SUCCESS",
    UPDATE_ADDRESS_FAILURE : "UPDATE_ADDRESS_FAILURE"

}
  export default {createNameTag, createAgeTag,createLocationTag, createGuestsTag, createAddressTag}